import './globals.css'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from './sessionProvider'
import { StateContext } from './context/stateContext'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
      <NextAuthProvider>
          <StateContext>
            {children}
          </StateContext>
        </NextAuthProvider>
      </body>
    </html>
  )
}
